### ISSUE TITLE
Austalian Data Incomplete And bad

### ISSUE THREAD

**Issue by dawesi** [sagarshirbhate/Country-State-City-Database#2]
The Australian Data is completely wrong.

There are 6 States and 2 Territories in Australia (https://gist.github.com/nickhough/b6067b7460e6d70a6996)

This is a list of cities and states, and Perth for instance only has 3 suburbs? #really and Collingwood is a suburb of Melbourne of Victoria (state)

**Comment by sagarshirbhate** [comment]
Hello @dawesi ,
Its Old database , Please do the changes and commit it I'll Approve it.
