### ISSUE TITLE
JSON file exist a error.

### ISSUE THREAD

**Issue by ZouTaooo** [sagarshirbhate/Country-State-City-Database#4]
The Santander state ==> City list exist a Null string(after the city Cabrera). It will occur json parse error.

**Comment by sagarshirbhate** [comment]
Can you please elaborate.
There is no null strings inside the database.

**Comment by ZouTaooo** [comment]
![H~Y5$JA7CSU3R1~TFNY}CIS](https://user-images.githubusercontent.com/28475389/124080141-9bd29080-da7c-11eb-8b7c-f02ac462e378.png)
I am sorry, it will not cause parse error, but it is really empty.

**Comment by sagarshirbhate** [comment]
Which database are you referring ?
Sqlite , XML or Plist ?

**Comment by ZouTaooo** [comment]
the file Countries.json

**Comment by sagarshirbhate** [comment]
Fixed !
